export class EventTypes {
    static CREATE_PROCESS_INSTANCE = "CREATE_PROCESS_INSTANCE"
    static CREATE_PROCESS_VARIABLES = "CREATE_PROCESS_VARIABLES"
    static CLOSE_PROCESS_INSTANCE = "CLOSE_PROCESS_INSTANCE"
    static FAIL_PROCESS_INSTANCE = "FAIL_PROCESS_INSTANCE"
    static BULK_CREATE_SEQUENCE_FLOWS = "BULK_CREATE_SEQUENCE_FLOWS"
    static RELEASE_PROCESS_INSTANCE_LOCK = "RELEASE_PROCESS_INSTANCE_LOCK"
    static CREATE_CATCH_EVENT_TASK = "CREATE_CATCH_EVENT_TASK"
}