export class EventTypes {
    static CREATE_PROCESS_INSTANCE = "CREATE_PROCESS_INSTANCE"
    static CREATE_PROCESS_VARIABLES = "CREATE_PROCESS_VARIABLES"
    static CLOSE_PROCESS_INSTANCE = "CLOSE_PROCESS_INSTANCE"
    static FAIL_PROCESS_INSTANCE = "FAIL_PROCESS_INSTANCE"
    static BULK_CREATE_SEQUENCE_FLOWS = "BULK_CREATE_SEQUENCE_FLOWS"
}