export class EventTypes {
    static CREATE_PROCESS_INSTANCE = "CREATE_PROCESS_INSTANCE"
    static CLOSE_PROCESS_INSTANCE = "CLOSE_PROCESS_INSTANCE"
    static FAIL_PROCESS_INSTANCE = "FAIL_PROCESS_INSTANCE"
}